### ISSUE TITLE
conflict between r-rvg and mro-base

### ISSUE THREAD

**Issue by AniketKul** [conda-forge/r-rvg-feedstock#2]
I am trying to install `r-rvg=0.1.*` in conda environment.

```OS: Ubuntu 16.04```

conda environment details:

```
(rstudio) root@rstudio-akulkarn-axhbs-7f7fccbb55-dghzz:/etc/ansible/59486474-155d-11e9-8995-02b1ade52008# conda info

     active environment : rstudio
    active env location : /usr/local/Anaconda3-5.3.1-Linux-x86_64/envs/rstudio
            shell level : 1
       user config file : /root/.condarc
 populated config files : /etc/conda/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.1.final.0
       base environment : /usr/local/Anaconda3-5.3.1-Linux-x86_64  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/Anaconda3-5.3.1-Linux-x86_64/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/Anaconda3-5.3.1-Linux-x86_64/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.1 Linux/3.10.0-957.1.3.el7.x86_64 ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False

(rstudio) root@rstudio-akulkarn-axhbs-7f7fccbb55-dghzz:/etc/ansible/59486474-155d-11e9-8995-02b1ade52008# python -V 
Python 3.6.6
(rstudio) root@rstudio-akulkarn-axhbs-7f7fccbb55-dghzz:/etc/ansible/59486474-155d-11e9-8995-02b1ade52008# 
```

I am using ansible to run tasks: 

Variable Setting in ansible: 

```{{ rstudio_env_name }}: rstudio```

r-rvg installation task looks like this:

```
- name: Install r-rvg
  become: yes
  become_user: root
  block:
    - with_items:
        - p: r-rvg=0.1.*
          c: conda-forge
      shell: bash -l -c '/usr/local/anaconda/bin/conda install -n {{ rstudio_env_name }} -c {{ item.c | default("default") }} -y {{ item.p }}'
```

Before r-rvg installation task, I am running mro-base installation task like this:

```
- name: Install mro-base
  become: yes
  become_user: root
  block:
    - with_items:
        - p: mro-base=3.5.*
      shell: bash -l -c '/usr/local/anaconda/bin/conda install -n {{ rstudio_env_name }} -c {{ item.c | default("default") }} -y {{ item.p }}'
```

### Order of tasks: 
1] mro-base installation task 
2] r-rvg installation task

mro-base installation works fine. But r-rvg installation fails. Error is as follows: 

![r-rvg_failure](https://user-images.githubusercontent.com/21697139/52005919-b6ede000-247f-11e9-9781-238fa094bc07.png)

### Order of tasks: 
1] r-rvg installation task
2] mro-base installation task

r-rvg installation works fine. But mro-base installation fails. Error is as follows:

![mro_base_fails](https://user-images.githubusercontent.com/21697139/52005826-7d1cd980-247f-11e9-80d8-dadbab8890ca.png)

## Additional Information:

mro-base is crucial for us. Hence, we cannot remove it. 

Any help is appreciated. Thanks!
